### ISSUE TITLE
.eps-Files on Win10 not rendered, when envp variable is populated before calling XfoObj.execute()

### ISSUE THREAD

**Issue by sermo-de-arboribus** [AntennaHouse/Alternate-XfoJavaCtl#12]
I am observing a strange behaviour when using XfoObj (exec-spec branch) with a PrintCSS setup that contains images in .eps format.

The formatter-config contains an entry for handling .eps-files - it doesn't matter if Distiller or Ghostscript is used:
`<pdf-settings EPS-processor="distiller"/>`
or 
`<pdf-settings EPS-processor="ghostscript" ghostscript="C:\Program Files\gs\gs9.27\bin\gswin64.exe"/>`

If the XfoObj `envp` field contains any entries before calling `execute()`, the AH Formatter tries to create .eps-Temp files in the Windows installation folder C:\WINDOWS, where it doesn't have write permissions. So the .eps handling fails with an error:

> [2020-10-26 10:16:20] [SEVERE ] Cannot create temporary file: C:\WINDOWS\ahgraE77c_1cba.eps (cannot create)

If  `envp` is an empty ArrayList at the moment of calling `execute()`, this problem does not occur: The .eps files are embedded into the PDF output of the Formatter without any issues. 

So the problem must be in the two distinctive if-else branches starting from line 617 (https://github.com/AntennaHouse/Alternate-XfoJavaCtl/blob/spec-exec/src/jp/co/antenna/XfoJavaCtl/XfoObj.java#L617). Can anybody tell me, why executing AHF via `this.r.exec()` fails to handle .eps files and executing via `pb.start()` in the other branch doesn't have this problem? Is there any environment variable that I could manually set to tell the Formatter where to store temporary .eps files? By the way: I can confirm that the problem even occurs, when the `envp` array contains the same Path as the one generated in https://github.com/AntennaHouse/Alternate-XfoJavaCtl/blob/9914d9c241e99a0bcb00426c09dc46efbddd6c5c/src/jp/co/antenna/XfoJavaCtl/XfoObj.java#L646 and the same AHF environment variables as the ones listed in the Windows system.

**Comment by brugal** [comment]
Thank you for the report and sorry for the delay.   I'll take a look at this.  It's probably due to exec() not inheriting environment variables like TMP and TEMP.

**Comment by sermo-de-arboribus** [comment]
The delay was no problem, as we're running with my temporary fix for the time being... On the other hand: I am new to AHF and XfoJavaCtl, so I'd be glad to hear from your expert examination into the problem, which will likely result in a better correction.

**Comment by brugal** [comment]
change added, thanks again!

**Comment by brugal** [comment]
render() method also needs the same fix:

https://github.com/AntennaHouse/Alternate-XfoJavaCtl/commit/acd025e01c04874b05804edca4aefc9fa14a58b3

**Comment by sermo-de-arboribus** [comment]
Thank you Brugal, I'll update our fork as soon as possible to benefit from your additional fixes.
