### ISSUE TITLE
`XfoObj(null)` fails to render while `XfoObj("")` works well

### ISSUE THREAD

**Issue by tofi86** [AntennaHouse/Alternate-XfoJavaCtl#2]
Hi @brugal,

this is a reply to [AH #12840] but my email was recognized as spam :-( So here we go in GitHub then...

We just tested the newly introduced `XfoObj("AHF63_HOME")` constructor and it works on Windows.
Well, almost.

Antenna House rendering will fail when you call `new XfoObj(null)` which should of course trigger the fallback solution. And as far as I've read and understood your code changes, there are mechanisms which check for `null`, but still it fails.

However, it works when using `new XfoObj("")` so that's a workaround for us at the moment.

Regards,
Tobias

/cc @christin-goetz

**Comment by brugal** [comment]
Thanks Tobias.  Verified that process initialization was incorrect when XfoObj() was null or empty.  It should be fixed with this patch:

https://github.com/AntennaHouse/Alternate-XfoJavaCtl/commit/cb66a4744c7d18b75461be8e6eef60efa210dfae
