### ISSUE TITLE
[spec-exec] relative path to ICC profile in AHFSettings.xml not supported

### ISSUE THREAD

**Issue by tofi86** [AntennaHouse/Alternate-XfoJavaCtl#8]
Hi,

we're using the `spec-exec` branch from your repo and we encountered an issue when trying to produce an PDF/X-4 with an ICC profile with the following setting:

```xml
<?xml version="1.0"?>
<!-- Settings AH Formatter V6.6 -->
<formatter-config>
	<pdf-settings pdf-version="PDF/X-4:2010"
		default-output-intent="PSO_Uncoated_ISO12647_eci.icc"
		embed-std-output-intent="PSO_Uncoated_ISO12647_eci.icc"
	/>
	<formatter-settings thin-space-width="0.125" hair-space-width="0.08333" />
</formatter-config>
```

The profile itself can be loaded from the ECI.org website, section old profiles.

It works when specifying an absolute path in the settings file, but this is not possible in production for other reasons.
With a relative path, we get the following error:

```
PDF output error (3352).
Color profile is empty (4):
```
With no more content.

Our Java code where we call this looks like this (abstract):

```java
// AHF66_64_HOME = C:\Program Files\Antenna House\AHFormatterV66
XfoObj axfo =new XfoObj("AHF66_64_HOME", null);
axfo.setExitLevel(4);
axfo.setMessageListener(msgListener);
// baseDir contains the XML file, the AHFSettings.xml and the ICC profile
axfo.setBaseURI(baseDir.getAbsoluteFile().toURI().toString());
axfo.addOptionFileURI(new File(baseDir, "AHFSettings.xml").getAbsolutePath());

// CSS Rendering
axfo.setFormatterType(XfoObj.S_FORMATTERTYPE_XMLCSS);  // -f
axfo.setDocumentURI(xmlInput.getAbsolutePath());
axfo.setOutputFilePath(pdfOutput.getAbsolutePath());
// iterate over List<File> cssStylesheets and add all stylesheets (typically 1-2)
for(File css : cssStylesheets) {
	axfo.addUserStylesheetURI(css.getAbsolutePath());  // -css
}
axfo.execute();
```

What are we doing wrong?

Did we forget to set a specific option? Or anything else?

Thanks for your help!

Best,
Tobias

**Comment by tofi86** [comment]
Seems like adding `pb.directory(workDir)` to the `ProcessBuilder` in https://github.com/AntennaHouse/Alternate-XfoJavaCtl/blob/spec-exec/src/jp/co/antenna/XfoJavaCtl/XfoObj.java#L553 solves the problem.

However, this requires a new setter for the workingDirectory. Any chance this can be added to the code?

**Comment by brugal** [comment]
Thanks Tobias, the patch looks good.  Is it ok to remove the error checks and let ProcessBuilder start() catch it?  With the current checks a deleted directory after setWorkingDir() is just ignored silently:

obj.setWorkingDir(new File("/share/data1"));
//  ...  delete /share/data1
obj.execute()

**Comment by tofi86** [comment]
Good catch. Remove it.

**Comment by brugal** [comment]
https://github.com/AntennaHouse/Alternate-XfoJavaCtl/commit/808b5cac1334731e8273739573333ce4e551171c

**Comment by tofi86** [comment]
Thanks! 👍

**Comment by brugal** [comment]
Bug fix for 'workingDir' when a specified or default unix Formatter installation is used:

https://github.com/AntennaHouse/Alternate-XfoJavaCtl/commit/e8f10541c4ad69e782d07aa8b36352d540f7d8dd

**Comment by tofi86** [comment]
Good catch! Thanks.
